from rich.markup import escape, render


def test_escape():
    assert escape("") == ""
    assert escape("foo") == "foo"
    assert escape("[b]") == r"\[b]"
    assert escape("[b]foo[/b]") == r"\[b]foo\[/b]"
    assert escape(r"\[b]") == r"\\\[b]"
    assert escape(r"\[b]") == r"\\\[b]"
    assert escape(r"\\[b]") == r"\\\\\[b]"
    assert escape(r"\\\[b]") == r"\\\\\\\[b]"
    assert escape(r"\\\[b]") == r"\\\\\\\[b]"
    assert escape(r"\\\\[b]") == r"\\\\\\\\\[b]"
    assert escape("[/b]") == r"\[/b]"
    assert escape(r"\[/b]") == r"\\\[/b]"
    assert escape("[b] [i]") == r"\[b] \[i]"
    assert escape("[b]foo [i]bar[/i][/b]") == r"\[b]foo \[i]bar\[/i]\[/b]"
    assert escape(r"\\") == r"\\\\"


def test_render():
    assert render("") == render("")
    assert render("[[b]]") == render("[b]")
    assert render("[[b]]") == render("[b]")
    assert render("[[[b]]]") == render("[[b]]")
    assert render("[[b]]foo") == render("[b]foo")
    assert render("[b]x[[b]]") == render("[b]x[b]")

    assert render("[b]foo") == render("[b]foo")
    assert render("[b]foo[b]") == render("[b]foo[b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo [i]bar") == render("[b]foo [i]bar")
    assert render("[b]foo [i]bar[i]") == render("[b]foo [i]bar[i]")
    assert render("[b]foo [i]bar[/i][/b]") == render("[b]foo [i]bar[/i][/b]")
    assert render("[b]foo [i]bar[i][/b]") == render("[b]foo [i]bar[i][/b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")
    assert render("[b]foo [i]bar[i][b]") == render("[b]foo [i]bar[i][b]")

    assert render(r"\[b]") == render("[b]")
    assert render(r"\[b]foo") == render("[b]foo")
    assert render(r"\[b]foo[/b]") == render("[b]foo[/b]")
    assert render(r"\[b]foo[i]bar[/i]\[/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\[/i][/b]") == render("[b]foo[i]bar[/i][/b]")

    assert render(r"\\") == render("\\")
    assert render(r"\\[b]") == render("\\[b]")
    assert render(r"\\[b]foo") == render("\\[b]foo")
    assert render(r"\\[b]foo[/b]") == render("\\[b]foo[/b]")
    assert render(r"\\[b]foo[i]bar[/i]\[/b]") == render("\\[b]foo[i]bar[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")
    assert render(r"[b]foo[i]bar\\[/i][/b]") == render("[b]foo[i]bar\\[/i][/b]")

    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")

    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")

    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")
    assert render(r"\\\[/b]") == render("\\[/b]")

    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")

    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")

    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")

    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")
    assert render("[b]foo[/b]") == render("[b]foo[/b]")